apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-webhook
webhooks:
  - name: resource-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        resource-webhook-enabled: "true"
    clientConfig:
      service:
        name: resource-webhook
        namespace: default
        path: "/mutate"
        port: 8080
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVZRENDQTBpZ0F3SUJBZ0lVS1Y2WG80U1pMTW1KdCtHL250WmRWQXMwZlQ0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1V6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVUTUJFRwpBMVVFQ2d3S1FXTnRaU3dnU1c1akxqRVZNQk1HQTFVRUF3d01RV050WlNCU2IyOTBJRU5CTUI0WERUSTBNREl5Ck56QTVNVGd3T0ZvWERUSTFNREl5TmpBNU1UZ3dPRm93Y1RFTE1Ba0dBMVVFQmhNQ1EwNHhDekFKQmdOVkJBZ00KQWtkRU1Rc3dDUVlEVlFRSERBSlRXakVUTUJFR0ExVUVDZ3dLUVdOdFpTd2dTVzVqTGpFek1ERUdBMVVFQXd3cQpjbVZ6YjNWeVkyVXRkMlZpYUc5dmF5NWtaV1poZFd4MExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNTdkpPV0JWNmNYdnBzRS91THp4UklYNHlwamMKbjBXY0QxakxrU3hpalFYcDRncEt1SFI0bFpZNUt5QUZPalpkNjNTT1RjUTMxZmxVV3pkVGYvOVlwY2lUa09RNwp1YStPVGt3YkxlVWlQck83Vk03dThoTFZ5ZmRGZit0a0FiNExZOGRIZlFVTVU2WXc2Y2dqSTdqZ1VxTmtjeGR6Cm5ienRYZVZKSTRqTThmZC9xM0RvYTZJTGgrMGJsVU1yNytCSVduNUhnbC8wQnR4TDViRnEzWGVvZXMxb1V3cGQKbzd3WGtCaEZXK3ExVlhWVjU2dHljYzF5eHhjZllaUDFNaGFjTmFGQ09mTWlmWmIrVjc5MTJ1aFgvRUhQTkhQNAo4U1FVTEFENzZoUnhDaTArRjhGdXNOVmtrNThyL1RqU2pIK29MUndBL0s3Vjk4ZWlCSTZ0b2F3VFp3SURBUUFCCm80SUJERENDQVFnd2djVUdBMVVkRVFTQnZUQ0J1b0lxY21WemIzVnlZMlV0ZDJWaWFHOXZheTVrWldaaGRXeDAKTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzZ2lSeVpYTnZkWEpqWlMxM1pXSm9iMjlyTG1SbFptRjFiSFF1YzNaagpMbU5zZFhOMFpYS0NISEpsYzI5MWNtTmxMWGRsWW1odmIyc3VaR1ZtWVhWc2RDNXpkbU9DSEhKbGMyOTFjbU5sCkxYZGxZbWh2YjJzdVpHVm1ZWFZzZEM1emRtT0NHSEpsYzI5MWNtTmxMWGRsWW1odmIyc3VaR1ZtWVhWc2RJSVEKY21WemIzVnlZMlV0ZDJWaWFHOXZhekFkQmdOVkhRNEVGZ1FVRXBZYUo4T1dlbGtWa0c1ajVQNFBHa1JiVXhZdwpId1lEVlIwakJCZ3dGb0FVSWJocGxLcFJsbzJHVlhHVStVeVMyeXdrTW1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSnY1M2JNMThFNWd4QjhWemE3ZTNqanpqd2ZCQmdOdUJScG1FOVI2SjJLZGI3eGpvTis4Y2VOck5yS3gKc3lFWU40MUswMGFOKzQwd3ZpU0xrTGhDTmtWNTN1WFhEOFIxQ1ljSS8zUlRKMUltN3NrOVI3eEdHeGE0Ulcxdwpvc3c3c1ZQazlFdEdFZzJLVzFlVFlUanVsaExQVS9zKzZ6c25oOWtxT3JuZC8xN04xNEVjRlIyWU1wMlZ3T1VJClVaUjBiTGk0dy92MDRRNWVFV1ZXdkl0N3ZlZG1CcnpFcUFRWEJKQ0xXdDZucWc5dVNxRm02d05ZVWhoT0JDUWcKOHBPMElmS1g4YnMzTVlFMnVOdWhPZVdhWXhta2s3ZGpyU3J5U0VYSUtxT0J2V3VyZnREVGV2c2h0NjVkUklITwo2RHZPMmRNNkwrSmdJZWU0ZWxLbVpuSG5zYms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE","UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
